<table id="parkway" class="table table-hover mb-0">
	<thead>
		<tr>




			<th>Amount Paid</th>
			<th>Actions</th>
			<th></th>
		</tr>
	</thead>
	<tbody v-if="carts.length">
		<tr v-for="cart in carts">

			<!-- <td><span class="text-primary">{{booking.bookingUid.toUpperCase()}}</span></td> -->
			<!-- <td></td> -->
			<td>{{cart.productName}}</td>
			<td>&#8358;{{cart.price}}</td>

			<td class="td-actions"><a href="#"><i class="la la-close delete"></i></a></td>
		</tr>

		<tr>

			<td></td>
			<td></td>
			<td></td>
		</tr>

		<tr>

			<td>Discount</td>
			<td><input type="text" v-model="code" ref="discount" @input="postdiscount()" class="form-control"></td>
			<td></td>
		</tr>

		<tr>

			<td>TOTAL</td>
			<td>{{totalPrice}}</td>
			<td></td>
		</tr>






	</tbody>
</table>

<script>
	let parkway = new Vue({
		el: "#parkway",
		data() {
			return {
				hey: "Love",
				carts: [],
				totalPrice: 0,
				code:""
			}
		},

		mounted() {
			this.getcart();
			this.gettotal();
		},

		methods: {
			getcart() {
				axios.get("/application/index/cart").then(res => {
					this.carts = res.data.cart;
				})
			},


			gettotal() {
				axios.get("/application/index/totalprice").then(res => {
					this.totalPrice = res.data.price;
				})
			},

			postdiscount(){
				let formData = new FormData();
				formData.append("price", this.totalPrice);
				formData.append("code", this.code);
				axios.post("/application/index/discount", formData).then(res=>{
					this.totalPrice = res.data.discount;
				})
			}
		},


	});
</script>